### ISSUE TITLE
Add "Category" validations

### ISSUE THREAD

**Issue by bmchrist** [crmcclar/acorn#9]
Validations on the category field on containers to make sure it's only one of a certain set of predefined categories

Bonus points if you turn the category input field into a select field that uses those same options

Only do this if we want to limit the set of categories to keep it consistent

Otherwise we can change this one to just be autocomplete on categories when typing one in based on past categories.

**Comment by crmcclar** [comment]
Used drop down of predefined categories
<%= f.label :category %><br>
<%= f.select :category, options_for_select([['Places','Places'], ['Food','Food'], ['Music','Music'], ['Thoughts','Thoughts']]) %>
